version: '3.9'

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db 
  
  # Node.js API Service
  api:
    build: .
    ports:
      - 5000:3000
    volumes:
      - .:/usr/src/app 
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      MONGO_DB: collectionDB
      JWT_SECRET: zQDfWv0r68eBP1DFJv70MhOBPSeN1waC
      ACCESS_TOKEN_EXPIRY: 1h
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
